# NumPy Tutorial

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, 
because it has one axis. That axis has a length of 3. 
In the example pictured below, the array has rank 2 (it is 2-dimensional). 
The first dimension (axis) has a length of 2, the second dimension has a length of 3.

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

NumPy’s array class is called ndarray. 
It is also known by the alias array. 
Note that numpy.array is not the same as the Standard Python Library class array.array, 
which only handles one-dimensional arrays and offers less functionality. 
The more important attributes of an ndarray object are:

In [2]:
import numpy as np

numpy.arange(start,stop,step,dtype)
- Return evenly spaced values within a given interval.

numpy.reshape(a,newshape)
- Gives a new shape to an array without changing its data.

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

ndarray.shape
- The dimensions of the array.
- This is a tuple of integers indicating the size of the array in each dimension.
- For a matrix with n rows and m columns, shape will be (n,m). 
- The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

In [5]:
a.shape


(3, 5)

ndarray.ndim
- The number of axes (dimensions) of the array. 
- In the Python world, the number of dimensions is referred to as rank.

In [6]:
a.ndim

2

ndarray.dtype
- An object describing the type of the elements in the array. 
- One can create or specify dtype’s using standard Python types. 
- Additionally NumPy provides types of its own. numpy.int32, numpy.int16,and numpy.float64 are some examples.

ndarray.itemsize
- The size in bytes of each element of the array.
- For example, an array of elements of type float64 has itemsize 8 (=64/8),while one of type complex32 has itemsize 4 (=32/8).
- It is equivalent to ndarray.dtype.itemsize.

In [7]:
a.itemsize

8

ndarray.size
- The total number of elements of the array. 
- This is equal to the product of the elements of shape.

In [8]:
a.size

15

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

ndarray.data
- The buffer containing the actual elements of the array. 
- Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

# Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular 
Python list or tuple using the array function. 
The type of the resulting array is deduced from 
the type of the elements in the sequences.

In [11]:
a = np.array([2,3,4])
a


array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([1.2, 3.5, 5.1])


In [14]:
b.dtype

dtype('float64')

In [15]:
a+b

array([3.2, 6.5, 9.1])

In [16]:
a*b

array([ 2.4, 10.5, 20.4])

In [18]:
a**2

array([ 4,  9, 16])

numpy.dot
- Dot product of two arrays. 

In [19]:
d=np.dot(a,b)
d

33.3

In [20]:
c=np.array([a,a**2])
c

array([[ 2,  3,  4],
       [ 4,  9, 16]])

In [21]:
c.shape

(2, 3)

ndarray.T
- Array property returning the array transposed. 

In [22]:
c.T

array([[ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [23]:
c.T.shape

(3, 2)

In [24]:
c.dtype

dtype('int64')

ndarray.astype
- Copy of the array, cast to a specified type.

In [25]:
c.astype(float)

array([[ 2.,  3.,  4.],
       [ 4.,  9., 16.]])

numpy.sum
- Sum of array elements over a given axis.

In [26]:
d=np.array([1,2,3,4,5])
d.sum()

15

ndarray.max
- Return the maximum along a given axis.

In [27]:
d.max()

5

ndarray.min
- Return the minimum along a given axis.

In [28]:
d.min()

1

numpy.mean
- Compute the arithmetic mean along the specified axis.
- Returns the average of the array elements. 

In [29]:
d.mean()

3.0

numpy.std
- Compute the standard deviation along the specified axis.

In [30]:
d.std()

1.4142135623730951

numpy.argmax
- Returns the indices of the maximum values along an axis.

In [31]:
d.argmax()

4

ndarray.argmin
- Return indices of the minimum values along the given axis of array.

In [32]:
d.argmin()

0

In [33]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [34]:
##column notation to get a range
s[0],s[4],s[0:3],s[1:5]

(0, 16, array([0, 1, 4]), array([ 1,  4,  9, 16]))

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-2]#starting from 5th to end and coming back to 2

array([64, 36, 16,  4,  0])

numpy.resize(a,newshape)
- Return a new array with the specified shape.

In [38]:
r=np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [39]:
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

When to use reshape and when resize?.

Both reshape and resize change the shape of the numpy array; the difference is that using resize will affect the original array while using reshape create a new reshaped instance of the array.

In [40]:
r[2,2]

14

In [41]:
r[3,3:6]

array([21, 22, 23])

In [44]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [46]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
r>30

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [48]:
#conditional indexing
r[r>30]

array([31, 32, 33, 34, 35])

In [49]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [50]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [51]:
##setting all elements to zero
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
#but the original where the slice has changed also changed
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [53]:
#to create copy of an array
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [54]:
#setting all elements to ten
r_copy[:]=10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [55]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

numpy.random.randint(low,high,size,dtype)
- Return random integers from low (inclusive) to high (exclusive).
- Return random integers from the “discrete uniform” distribution of the specified dtype.

In [56]:
###Iterating over arrays
#create 4x3 array of random numbers from zero through nine
test=np.random.randint(0,10,(4,3))
test

array([[5, 8, 0],
       [5, 0, 2],
       [5, 2, 9],
       [0, 0, 2]])

In [58]:
#iterate by row
for row in test:
    print(row)

[5 8 0]
[5 0 2]
[5 2 9]
[0 0 2]


In [60]:
len(test)

4

In [59]:
for i in range(len(test)):     ###iterate using len function of test
    print(test[i])

[5 8 0]
[5 0 2]
[5 2 9]
[0 0 2]


numpy.ndenumerate(arr)
- Multidimensional index iterator.
- Return an iterator yielding pairs of array coordinates and values.

In [61]:
enumerate(test)

In [62]:
##to combine these two ways of iterating use enumeration
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [5 8 0]
row 1 is [5 0 2]
row 2 is [5 2 9]
row 3 is [0 0 2]


In [63]:
test2=test**2
test2

array([[25, 64,  0],
       [25,  0,  4],
       [25,  4, 81],
       [ 0,  0,  4]])

In [65]:
zip(test, test2)

In [66]:
?zip

In [67]:
##to iterate over both arrays using zip
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[5 8 0] + [25 64  0] = [30 72  0]
[5 0 2] + [25  0  4] = [30  0  6]
[5 2 9] + [25  4 81] = [30  6 90]
[0 0 2] + [0 0 4] = [0 0 6]


A frequent error consists in calling array with multiple numeric arguments,
rather than providing a single list of numbers as an argument.

In [68]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

array transforms sequences of sequences into two-dimensional arrays, 
sequences of sequences of sequences into three-dimensional arrays, and so on.

In [69]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [70]:
b.ndim

2

The type of the array can also be explicitly specified at creation time:

In [72]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [74]:
z1 = np.zeros(shape= (3,4) )
z1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
z1.dtype

dtype('float64')

In [76]:
# to create much larger arrays and arrays with different shapes.
p=np.ones( shape=(2,3,4), dtype=np.int16 )                # depth=2,rows=3,columns=4 ,dtype can also be specified
p

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [77]:
p.dtype

dtype('int16')

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
- Return a 2-D array with ones on the diagonal and zeros elsewhere.
- where N -no: of rows,M -no:of columns,C -whether output in C-style or Fortran-style.

In [78]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

numpy.diag(v, k=0)
- Extract a diagonal or construct a diagonal array.
- v : array_like.If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.
- k : int, optional.Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.


In [79]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [80]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

numpy.repeat(a, repeats, axis=None)
- Repeat elements of an array.

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

numpy.empty(shape, dtype=float, order='C')
- Return a new array of given shape and type, without initializing entries.
- The values or content of the created array will be random and will need to be assigned before use.

In [ ]:
np.empty( (2,3) )                                 # uninitialized, output may vary
                                                    #random

array([[ 2.,  3.,  4.],
       [ 4.,  9., 16.]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [ ]:
np.arange( 10, 30, 5 )
#np.arange( 1, 30, 2 )


array([10, 15, 20, 25])

In [ ]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

numpy.linspace(start, stop, num=50)
- Return evenly spaced numbers over a specified interval.
- Returns num evenly spaced samples, calculated over the interval.
- num : int, optional.Number of samples to generate. Default is 50. Must be non-negative.

In [ ]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [ ]:
?np.linspace

In [ ]:
f = np.sin(x)

In [ ]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

# Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [ ]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [ ]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c = np.arange(24).reshape(2,3,4)         # 3d array,depth=2,row=3,columns=4
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [ ]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.arange(10000).reshape(100,100))  ##get a truncated representation.

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

numpy.set_printoptions
- Set printing options.
- These options determine the way floating point numbers, arrays and other NumPy objects are displayed.
- threshold : int, optional.Total number of array elements which trigger summarization rather than full repr (default 1000).

In [ ]:
np.set_printoptions(threshold=np.inf) #to get full array set threshold as np.nan or np.inf

In [ ]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63   64   65   66   67   68   69
    70   71   72   73   74   75   76   77   78   79   80   81   82   83
    84   85   86   87   88   89   90   91   92   93   94   95   96   97
    98   99]
 [ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
   114  115  116  117  118  119  120  121  122  123  124  125  126  127
   128  129  130  131  132  133  134  135  136  137  138  139  140  141
   142  143  144  145  146  147  148  149  150  151  152  153  154  155
   156  157  158  159  160  161  162  163  164  165  166  167  168  169
   170  171  172  173  174  175  176  177  178  179  180  181  182  183
   184  185  186  187  188  189  190  191  192  193

In [ ]:
np.set_printoptions(threshold=100)

In [ ]:
print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [ ]:
c = a-b
c

array([20, 29, 38, 47])

In [ ]:
b**2

array([0, 1, 4, 9])

numpy.sin
- Trigonometric sine, element-wise.

In [ ]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method:

In [ ]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B                   # matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
np.dot(A, B)                # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [ ]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
print(b)

[[3 3 3]
 [3 3 3]]
[[0.76365759 0.1259871  0.24309944]
 [0.78088915 0.06756039 0.98781261]]


In [ ]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
a *= 3
print(a)

[[9 9 9]
 [9 9 9]]


In [ ]:
b += a
b

array([[9.76365759, 9.1259871 , 9.24309944],
       [9.78088915, 9.06756039, 9.98781261]])

In [ ]:
a+=b                   ## b is not automatically converted to integer type,shows TypeError
b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [ ]:
c.dtype.name


'float64'

numpy.exp
- Calculate the exponential of all elements in the input array.

In [ ]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [ ]:
d.dtype.name

'complex128'

In [ ]:
d=d.astype('f')
d.dtype

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


dtype('float32')

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

numpy.random.random(size=None)
- Return random floats in the half-open interval (0.0,1.0)
- Results are from the “continuous uniform” distribution over the stated interval. 

In [ ]:
a = np.random.random((2,3))
a


array([[0.89589392, 0.72388628, 0.08657527],
       [0.3599386 , 0.6299188 , 0.3346242 ]])

In [ ]:
a.sum(axis=0)   #sum of each column

array([1.25583252, 1.35380509, 0.42119947])

In [ ]:
a.min(axis=1)    #min of each row

array([0.08657527, 0.3346242 ])

In [ ]:
a.max(axis=0) #sum of each column


array([0.89589392, 0.72388628, 0.3346242 ])

In [ ]:
a.cumsum(axis=1)   #cumulative sum along each row

array([[0.89589392, 1.6197802 , 1.70635547],
       [0.3599386 , 0.9898574 , 1.3244816 ]])

# Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [ ]:
B = np.arange(3)
B


array([0, 1, 2])

In [ ]:
np.exp(B)    #returns exponent of B

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
np.sqrt(B)    #returns square root of B

array([0.        , 1.        , 1.41421356])

In [ ]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

# Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
a[2]

8

In [ ]:
a[:6:2]


array([ 0,  8, 64])

In [ ]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [ ]:
a[ : :-1]                      # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [ ]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

numpy.fromfunction(function, shape,dtype)
- Construct an array by executing a function over each coordinate.

In [ ]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

 this is what happens -> 
	 1. 10 * 0 + 4 -> arange(4)
     2. 10 * 1 + 4 -> arange(14)
	 3. 10 * 2 + 4 -> arange(24)
	 4. 10 * 3 + 4 -> arange(34)
	 5. 10 * 4 + 4 -> arange(44) -> this is the last value returned, and the data shape should be a 5,4
 transform function,values to transform

In [ ]:
b[2,3]

23

In [ ]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [ ]:

b[ : ,1]                        # equivalent to the previous example


array([ 1, 11, 21, 31, 41])

In [ ]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

# Shape Manipulation

An array has a shape given by the number of elements along each axis:

numpy.floor
- Return the floor of the input, element-wise.
- The floor of the scalar x is the largest integer i, such that i <= x.

In [ ]:
a = np.floor(10*np.random.random((3,4)))
a


array([[1., 1., 2., 3.],
       [1., 5., 1., 8.],
       [8., 4., 4., 0.]])

In [ ]:
a.shape


(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

numpy.ravel(a, order='C')
- Return a contiguous flattened array.
- A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

In [ ]:
a.ravel()  # returns the array, flattened          

array([1., 1., 2., 3., 1., 5., 1., 8., 8., 4., 4., 0.])

In [ ]:
a          ##original array remains unchanged

array([[1., 1., 2., 3.],
       [1., 5., 1., 8.],
       [8., 4., 4., 0.]])

In [ ]:
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 1.],
       [2., 3.],
       [1., 5.],
       [1., 8.],
       [8., 4.],
       [4., 0.]])

In [ ]:
a             #original array remains unchanged

array([[1., 1., 2., 3.],
       [1., 5., 1., 8.],
       [8., 4., 4., 0.]])

In [ ]:

a.T  # returns the array, transposed


array([[1., 1., 8.],
       [1., 5., 4.],
       [2., 1., 4.],
       [3., 8., 0.]])

In [ ]:

a.T.shape


(4, 3)

In [ ]:

a.shape

(3, 4)

# Stacking together different arrays

Several arrays can be stacked together along different axes:

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

array([[0., 9.],
       [4., 8.]])

In [ ]:
b = np.floor(10*np.random.random((2,2)))
b

array([[5., 9.],
       [9., 0.]])

numpy.vstack(tup)
- Stack arrays in sequence vertically (row wise).
- tup : sequence of ndarrays

In [ ]:
np.vstack((a,b))         # vstack stacks along their first axes

array([[0., 9.],
       [4., 8.],
       [5., 9.],
       [9., 0.]])

numpy.hstack(tup)
- Stack arrays in sequence horizontally (column wise).

In [ ]:
np.hstack((a,b))         # hstack stacks along their second axes

array([[0., 9., 5., 9.],
       [4., 8., 9., 0.]])

# Splitting one array into several smaller ones

In [ ]:
a = np.floor(10*np.random.random((2,6)))
a

array([[9., 3., 4., 0., 8., 4.],
       [0., 8., 8., 6., 5., 9.]])

numpy.hsplit(ary, indices_or_sections)
- Split an array into multiple sub-arrays horizontally (column-wise).

In [ ]:
np.hsplit(a,3)

[array([[9., 3.],
        [0., 8.]]), array([[4., 0.],
        [8., 6.]]), array([[8., 4.],
        [5., 9.]])]

In [ ]:
np.hsplit(a,3)[0]   

array([[9., 3.],
       [0., 8.]])

In [ ]:
np.hsplit(a,3)[1] 

array([[4., 0.],
       [8., 6.]])

In [ ]:
np.hsplit(a,3)[2] 

array([[8., 4.],
       [5., 9.]])

In [ ]:
a                 #a remains unchanged after split

array([[9., 3., 4., 0., 8., 4.],
       [0., 8., 8., 6., 5., 9.]])

In [ ]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[9., 3., 4.],
        [0., 8., 8.]]), array([[0.],
        [6.]]), array([[8., 4.],
        [5., 9.]])]

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.

# Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

### No Copy at All

- Simple assignments make no copy of array objects or of their data

In [ ]:
a = np.arange(12)
print(a.shape)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

(12,)


True

In [ ]:
b.shape = 3,4    # changes the shape of a
print(a.shape)

(3, 4)


- Python passes mutable objects as references, so function calls make no copy.

In [ ]:
def f(x):
    print(id(x))

print(id(a))                           # id is a unique identifier of an object

print(f(a))


139727790066304
139727790066304
None


### View or Shallow Copy

- Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [ ]:
c = a.view()

In [ ]:
c is a

False

In [ ]:
c.base is a     # c is a view of the data owned by a

True

In [ ]:
c.flags.owndata

False

In [ ]:
c.shape = 2,6                      # a's shape doesn't change

In [ ]:
print(a.shape)

(3, 4)


In [ ]:
c[0,4] = 1234                      # a's data changes
print(a)

[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [ ]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

Slicing an array returns a view of it:

In [ ]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Deep Copy

- The copy method makes a complete copy of the array and its data.

In [ ]:
d = a.copy()                          # a new array object with new data is created


In [ ]:
d is a



False

In [ ]:
d.base is a                           # d doesn't share anything with a



False

In [ ]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])